[package]
name = "silly_ecs"
version = "0.1.0"
authors = ["wolfgang <wolfgang.deutsch@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
Inflector="*"

[dependencies.syn]
version = "1.0"
features = ["full"]
